#!/usr/bin/python3
#+
# Returns the size of C types with the specified names. Invoke
# this script as follows:
#
#     sizeof [«include» ...] «type» ...
#
# where the arguments are one or more type specs to determine
# the sizes of. The «include»s take the form of “-i«includefile»”
# or “--include=«includefile»” specifying include files that
# are needed to find the definitions of those types. The
# script compiles and runs a generated C program that prints
# out the sizes of the types.
#
# Example: the command
#
#     sizeof --include=sys/types.h pid_t uid_t gid_t
#
# reports the sizes of the pid_t, uid_t and gid_t types.
# These need to be defined by including <sys/types.h>, so
# that is specified in an --include directive. On a 64-bit
# system, you should see this output:
#
#     sizeof(pid_t) = 4
#     sizeof(uid_t) = 4
#     sizeof(gid_t) = 4
#
# Copyright 2020 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
# Licensed under CC-BY <http://creativecommons.org/licenses/by/4.0/>.
#-

import sys
import os
import subprocess
import tempfile
import shutil
import getopt

#+
# Useful stuff
#-

def ensure_reasonable_umask() :
    "ensures that the umask is set to a reasonable value, namely" \
    " that user always has read+write+execute access to files that" \
    " they create, while leaving the group- and other-access bits" \
    " unchanged. Returns the previous and new umask values, for" \
    " reference."
    ensure_clear_in_umask = 0o700
    oldmask = os.umask(0o077)
      # temporarily set to some safe value
    newmask = oldmask & ~ensure_clear_in_umask
    os.umask(newmask)
    return oldmask, newmask
#end ensure_reasonable_umask

#+
# Mainline
#-

includes = []
opts, args = getopt.getopt \
  (
    sys.argv[1:],
    "i:",
    ["include="]
  )
if len(args) == 0 :
    raise getopt.GetoptError("nothing to do")
#end if
for keyword, value in opts :
    if keyword == "-i" or keyword == "--include" :
        includes.append(value)
    #end if
#end for

ensure_reasonable_umask()
temp_dir = tempfile.mkdtemp(prefix = "sizeof-")
prev_dir = os.getcwd()
os.chdir(temp_dir)
srcfilename = "test.c"
exefilename = "test"
srcfile = open(srcfilename, "wt")
for include in includes :
    srcfile.write("#include <%s>\n" % include)
#end for
srcfile.write \
  (
    "#include <stdio.h>\n"
    "\n"
    "int main(int argc, char **argv)\n"
    "  {\n"
  )
for typespec in args :
    srcfile.write \
      (
            "    fprintf(stdout, \"sizeof(%(type)s) = %%d\\n\", sizeof(%(type)s));\n"
        %
            {"type" : typespec}
      )
#end for
srcfile.write \
  (
    "    return 0;\n"
    "  } /*main*/\n"
  )
srcfile.close()
done = subprocess.run \
  (
    args = ("gcc", "-o", exefilename, srcfilename)
  )
if done.returncode == 0 :
    done = subprocess.run \
      (
        args = ("./" + exefilename,),
        capture_output = True,
        text = True
      )
    if done.returncode == 0 :
        sys.stdout.write(done.stdout)
        sys.stdout.flush()
    #end if
#end if
os.chdir(prev_dir)
shutil.rmtree(temp_dir)
